# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# YAML Anchors to reduce copypasta

# This is necessary for job to run when a tag is created
filters_always: &filters_always
  filters:
    tags:
      only: /.*/

# Restrict running to only be on tags starting with vNNNN
filters_publish: &filters_publish
  filters:
    tags:
      only: /^v[0-9].*/
    branches:
      ignore: /.*/

filters_main_and_tags: &filters_main_and_tags
  filters:
    branches:
      only: main
    tags:
      only: /^v[0-9].*/

orbs:
  aws-cli: circleci/aws-cli@3.2.0

executors:
  go:
    parameters:
      goversion:
        type: string
        default: "22"
    working_directory: /home/circleci/go/src/github.com/honeycombio/agentless-integrations-for-aws
    docker:
      - image: cimg/go:1.<< parameters.goversion >>

jobs:
  go_test:
    executor: go
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    executor: go
    steps:
      - checkout
      - run: ./build.sh
      - persist_to_workspace:
          root: ./
          paths:
            - pkg
      - store_artifacts:
          path: ./pkg
  publish_aws:
    executor: go
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - aws-cli/setup:
          role-arn: "arn:aws:iam::702835727665:role/circleci-public-repos"
          role-session-name: "agentless-integrations-for-aws"
          aws-region: AWS_REGION
      - run: ./publish_aws.sh
  publish_github:
    docker:
      - image: cibuilds/github:0.13.0
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: "Draft GitHub Release"
          command: ghr -draft -n ${CIRCLE_TAG} -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./pkg/


# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  version: 2
  build:
    jobs:
      - go_test:
          <<: *filters_always
      - build:
          <<: *filters_always
          requires:
            - go_test
      - publish_aws:
          <<: *filters_main_and_tags
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
      - publish_github:
          <<: *filters_publish
          context: Honeycomb Secrets for Public Repos
          requires:
            - build
