AWSTemplateFormatVersion: "2010-09-09"
Description: This template builds the necessary lambda infra to send cloudwatch logs to honeycomb
Parameters:
  Environment:
    Type: String
    Default: ''
    Description: Name of environment. This will be included in log events sent to Honeycomb.
  HoneycombWriteKey:
    Type: String
    Description: Your Honeycomb write key. If KMSKeyId is set, this should be a Cyphertext Blob from KMS.
  KMSKeyId:
    Type: String
    Default: ''
    Description: 'KMS Key ID used to encrypt your Honeycomb write key (ex: a80d80aa-19b5-486a-a163-a4502b5555)'
  HoneycombAPIHost:
    Type: String
    Default: https://api.honeycomb.io
    Description: Optional. Altenative Honeycomb API host.
  HoneycombDataset:
    Type: String
    Default: rds-postgresql-logs
    Description: Target honeycomb dataset
  HoneycombSampleRate:
    Type: Number
    Default: 1
    Description: Sample rate. See https://honeycomb.io/docs/guides/sampling/.
  LogLinePrefix:
    Type: String
    Default: '%t:%r:%u@%d:[%p]:'
    Description: The prefix of each log line. See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html#USER_LogAccess.Concepts.PostgreSQL.Log_Format
  LogGroupName:
    Type: String
    Description: The name of the AWS Cloudwatch Log Group to subscribe to
  LogGroupName1:
    Type: String
    Default: ''
    Description: Additional log group to subscribe to
  LogGroupName2:
    Type: String
    Default: ''
    Description: Additional log group to subscribe to
  LogGroupName3:
    Type: String
    Default: ''
    Description: Additional log group to subscribe to
  LogGroupName4:
    Type: String
    Default: ''
    Description: Additional log group to subscribe to
  LogGroupName5:
    Type: String
    Default: ''
    Description: Additional log group to subscribe to
  FilterPattern:
    Type: String
    Default: ''
    Description: The filtering expressions that restrict which cloudwatch log lines get sent
  ScrubQuery:
    Type: String
    Default: false
    Description: Replaces the query field with a one-way hash of the contents
    AllowedValues:
      - true
      - false
  FilterFields:
    Type: String
    Description: Comma-separated simple strings to specify which field names to remove from events
    Default: ''
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - LogGroupName
          - HoneycombWriteKey
          - HoneycombDataset
          - HoneycombSampleRate
      - Label:
          default: Optional Parameters
        Parameters:
          - LogLinePrefix
          - LogGroupName1
          - LogGroupName2
          - LogGroupName3
          - LogGroupName4
          - LogGroupName5
          - Environment
          - KMSKeyId
          - FilterPattern
          - HoneycombAPIHost
          - ScrubQuery
          - FilterFields
Conditions:
  EncryptionEnabled: !Not [!Equals [!Ref KMSKeyId, '']]
  LogGroup1Enabled: !Not [!Equals [!Ref LogGroupName1, '']]
  LogGroup2Enabled: !Not [!Equals [!Ref LogGroupName2, '']]
  LogGroup3Enabled: !Not [!Equals [!Ref LogGroupName3, '']]
  LogGroup4Enabled: !Not [!Equals [!Ref LogGroupName4, '']]
  LogGroup5Enabled: !Not [!Equals [!Ref LogGroupName5, '']]
Resources:
  CloudwatchLambdaHandler:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket:
          "Fn::Join":
          - '-'
          -
            - honeycomb-integrations
            - !Ref "AWS::Region"
        S3Key: agentless-integrations-for-aws/LATEST/ingest-handlers.zip
      Description: Lambda function for sending rds cloudwatch logs to Honeycomb
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          HONEYCOMB_WRITE_KEY: !Ref HoneycombWriteKey
          KMS_KEY_ID: !Ref KMSKeyId
          API_HOST: !Ref HoneycombAPIHost
          DATASET: !Ref HoneycombDataset
          SAMPLE_RATE: !Ref HoneycombSampleRate
          SCRUB_QUERY: !Ref ScrubQuery
          LOG_LINE_PREFIX: !Ref LogLinePrefix
          FILTER_FIELDS: !Ref FilterFields
      FunctionName:
        "Fn::Join":
          - '-'
          -
            - CloudwatchLambdaHandler
            - !Ref "AWS::StackName"
      Handler: postgresql-handler
      MemorySize: 128
      Role:
        "Fn::GetAtt":
          - LambdaIAMRole
          - Arn
      Runtime: go1.x
      Timeout: 10
  ExecutePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      Principal: 'logs.amazonaws.com'
  CloudwatchSubscriptionFilter:
    Type: "AWS::Logs::SubscriptionFilter"
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  # hacky work-around to allow multiple optional inputs for log group name
  # clearly hitting some limitations of the Cloudformation workflow here
  CloudwatchSubscriptionFilter1:
    Type: "AWS::Logs::SubscriptionFilter"
    Condition: LogGroup1Enabled
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName1
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  CloudwatchSubscriptionFilter2:
    Type: "AWS::Logs::SubscriptionFilter"
    Condition: LogGroup2Enabled
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName2
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  CloudwatchSubscriptionFilter3:
    Type: "AWS::Logs::SubscriptionFilter"
    Condition: LogGroup3Enabled
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName3
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  CloudwatchSubscriptionFilter4:
    Type: "AWS::Logs::SubscriptionFilter"
    Condition: LogGroup4Enabled
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName4
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  CloudwatchSubscriptionFilter5:
    Type: "AWS::Logs::SubscriptionFilter"
    Condition: LogGroup5Enabled
    Properties:
      DestinationArn:
        "Fn::GetAtt":
          - CloudwatchLambdaHandler
          - Arn
      LogGroupName: !Ref LogGroupName5
      FilterPattern: !Ref FilterPattern
    DependsOn: ExecutePermission
  LambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  LambdaLogPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "lambda-create-log"
      Roles:
          - Ref: LambdaIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'
  LambdaKMSPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EncryptionEnabled
    Properties:
      PolicyName: "lambda-kms-decrypt"
      Roles:
          - Ref: LambdaIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              "Fn::Join":
                - ''
                -
                  - arn:aws:kms:*:*:key/
                  - !Ref KMSKeyId
