AWSTemplateFormatVersion: "2010-09-09"
Description: This template builds the necessary lambda infra send SNS events to Honeycomb
Parameters:
  Environment:
    Type: String
    Default: ''
    Description: Name of environment. This will be included in log events sent to Honeycomb.
  HoneycombWriteKey:
    Type: String
    Description: Your Honeycomb write key. If KMSKeyId is set, this should be a Cyphertext Blob from KMS.
  KMSKeyId:
    Type: String
    Default: ''
    Description: 'KMS Key ID used to encrypt your Honeycomb write key (ex: a80d80aa-19b5-486a-a163-a4502b5555)'
  HoneycombAPIHost:
    Type: String
    Default: https://api.honeycomb.io
    Description: Optional. Altenative Honeycomb API host.
  HoneycombDataset:
    Type: String
    Default: sns-events
    Description: Target honeycomb dataset
  HoneycombSampleRate:
    Type: Number
    Default: 1
    Description: Sample rate. See https://honeycomb.io/docs/guides/sampling/.
  TopicArn:
    Type: String
    Description: The ARN of the topic to subscribe to.
  TimeFieldName:
    Type: String
    Default: ''
    Description: Name of the field that contains a timestamp
  TimeFieldFormat:
    Type: String
    Default: ''
    Description: Timestamp format to use, if TimeFieldName is set. (strftime and Golang time.Parse supported)
  ErrorDataset:
    Type: String
    Default: ''
    Description: If set, write error events such as parsing errors to this dataset. Can be the same as your primary dataset.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - TopicArn
          - HoneycombWriteKey
          - HoneycombDataset
          - HoneycombSampleRate
      - Label:
          default: Optional Parameters
        Parameters:
          - Environment
          - KMSKeyId
          - ErrorDataset
          - TimeFieldName
          - TimeFieldFormat
          - HoneycombAPIHost
Conditions:
  EncryptionEnabled: !Not [!Equals [!Ref KMSKeyId, '']]
Resources:
  SNSLambdaHandler:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: honeycomb-builds
        S3Key: honeycombio/integrations-for-aws/LATEST/ingest-handlers.zip
      Description: Lambda function for sending sns events to Honeycomb
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PARSER_TYPE: json
          HONEYCOMB_WRITE_KEY: !Ref HoneycombWriteKey
          KMS_KEY_ID: !Ref KMSKeyId
          API_HOST: !Ref HoneycombAPIHost
          DATASET: !Ref HoneycombDataset
          SAMPLE_RATE: !Ref HoneycombSampleRate
          TIME_FIELD_NAME: !Ref TimeFieldName
          TIME_FIELD_FORMAT: !Ref TimeFieldFormat
          ERROR_DATASET: !Ref ErrorDataset
      FunctionName:
        "Fn::Join":
          - '-'
          -
            - SNSLambdaHandler
            - !Ref "AWS::StackName"
      Handler: sns-handler
      MemorySize: 128
      Role:
        "Fn::GetAtt":
          - LambdaIAMRole
          - Arn
      Runtime: go1.x
      Timeout: 10
  ExecutePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        "Fn::GetAtt":
          - SNSLambdaHandler
          - Arn
      Principal: 'sns.amazonaws.com'
  SNSSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint:
        "Fn::GetAtt":
            - SNSLambdaHandler
            - Arn
      Protocol: lambda
      TopicArn: !Ref TopicArn
  LambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  LambdaLogPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "lambda-create-log"
      Roles:
          - Ref: LambdaIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: 'arn:aws:logs:*:*:*'
  LambdaKMSPolicy:
    Type: "AWS::IAM::Policy"
    Condition: EncryptionEnabled
    Properties:
      PolicyName: "lambda-kms-decrypt"
      Roles:
          - Ref: LambdaIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              "Fn::Join":
                - ''
                -
                  - arn:aws:kms:*:*:key/
                  - !Ref KMSKeyId
